version: '2'
services:
    kibana:
        image: alibeibei/kibana:v1
        restart: always
        container_name: kibana
        ports:
            - "5601:5601"
        environment:
            SERVER_HOST: 0.0.0.0
            ES_URL: http://172.16.20.90:9200
