FROM fendouxiong/java18:latest
MAINTAINER  fendouxiong <wuxiaofei8023@gmail.com>

#安装javasdk
RUN yum install -y wget java-1.8.0-openjdk java-1.8.0-openjdk-devel && \
    echo "export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.x86_64" >> /etc/profile.d/java.sh && \
    echo "export CLASSPATH=.:$JAVA_HOME/jre/lib/rt.jar:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar" >> /etc/profile.d/java.sh && \
    echo "export PATH=$PATH:$JAVA_HOME/bin" >> /etc/profile.d/java.sh && \
    source /etc/profile.d/java.sh && \
    yum clean all



2018年6月3日朱鹏因买房向饶鑫鑫借款25000元，约定于2019年10月3日之前一次性偿还，并写下借条约定归还日期、利息和违约金。2019年4月15日朱鹏因资金周转向饶鑫鑫借款20000元，约定于2019年10月15前一次性偿还。并写下借条约定归还日期、利息和违约金。上述两笔借款到期后朱鹏均以没钱为由拒绝归还，之后饶鑫鑫多次催促朱鹏还钱，仅要回8000元，至此过后更是失联，长久不回复消息也不接电话。饶鑫鑫迫于无奈只能走法律程序来保护自己的合法利益，故特向贵院提起诉讼，请求判令如上诉求。